### ISSUE TITLE
Why not as outside collaborators?

### ISSUE THREAD

**Issue by ajsb85** [erickzhao/badge#3]
https://github.com/orgs/[org]/outside-collaborators

**Comment by erickzhao** [comment]
Hi @ajsb85! That's definitely a great feature to have. I'll definitely add it in as an option in the config. :)

**Comment by ajsb85** [comment]
Thanks.

We are using your bot in our org @flyve-mdm

https://git.io/vd5tO

**Comment by erickzhao** [comment]
@ajsb85 By the way, when I changed the name of the repo from `badge` to `invite-contributors`, I forgot to mention that in the README that the config file was changed from `badge.yml` to `invite-contributors.yml`.

If you want your config file to work, you'll have to rename it. Sorry about the inconvenience!

**Comment by ajsb85** [comment]
Ok, thank you @erickzhao 

/cc @naylin15

**Comment by erickzhao** [comment]
Update on progress @ajsb85:

I haven't had any prior experience with outside collaborators, so I could use a bit of clarification for what you think is useful. If I understand correctly, your use case is [adding people as outside collaborators to the specific repository they made a PR to](https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator)?

(I had originally tried to make them outside collaborators to a specific team within the org, but this didn't work because you can [only convert existing members to outside collaborators](https://developer.github.com/v3/orgs/outside_collaborators/#convert-member-to-outside-collaborator), so the flow of having `invite-contributors` invite someone to a team and automatically making them an outside contributor doesn't work.)

Also (@Naylin15), I realized that I had a big mistake in my README (also involving the `invite-contributors.yml` file). The correct usage of adding a team name is actually `team: MY TEAM NAME` instead of just `MY TEAM NAME` ([see this example repo](https://git.io/vdNfL)). Sorry for the inconvenience once again, I should have double-checked everything while writing my readme.

**Comment by erickzhao** [comment]
Update again @ajsb85! Sorry for the delay, but I've finally had time to implement the feature. My [latest push](https://github.com/erickzhao/invite-contributors/commit/b63576971f22530b133c55371436052f02894ab1) should make it happen. Just add `isOutside: true` to your `invite-contributors.yml` to add contributors as outside collaborators to your repos!

Please note that since I now have to be able to add collaborators to the repository, you'll be receiving a new permission request from `invite-contributors`! Check your junk mail if you haven't gotten the email (it went straight to junk for my test repo lol).
